progetto_tecnologie_web_2020/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', 'users')),
    path('admin/', admin.site.urls),
    path('songs/', include('songs.urls')),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from songs import views

app_name = 'songs'

urlpatterns = [
    path('feed/', views.feed, name='feed'),
    path('composer/<int:pk>/detail', views.ComposerDetailView.as_view(), name='composer-detail'),

    path('song/<int:pk>/detail', views.SongDetailView.as_view(), name='song-detail'),
    path('song/<int:pk>/modify', views.SongChangeView.as_view(), name='song-change'),
    path('song/<int:pk>/delete', views.SongDeleteView.as_view(), name='song-delete'),


    path('genre/<int:pk>/detail', views.GenreDetailView.as_view(), name='genre-detail'),

    path('insert_comment', views.insert_comment, name='insert-comment'),

    path('results', views.search, name='search'),
    path('get_genres', views.get_genres, name='get-genres'),
    path('get_songs', views.get_songs, name='get-songs'),
    path('get_composers', views.get_composers, name='get-composers'),

    path('following', views.following, name='following'),
    path('unfollow', views.unfollow, name='unfollow'),
    path('follow', views.follow, name='follow'),
    path('like', views.like, name='like'),


    path('become_composer', views.ComposerCreateView.as_view(), name='composer-create'),

    path('rankings', views.rankings, name="rankings"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('refresh-graph', views.get_data_to_graph, name="refresh-data")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.user_change_view, name='edit'),
    path('password/', views.change_password, name='change-psw'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from datetime import timedelta

from songs.decorators import composer_only
from songs.models import Song, Genre, Composer, Comment, Like
from users.models import User


@login_required
def feed(request):
    context = dict()

    user = request.user
    is_composer = user.username in [obj.user.username for obj in Composer.objects.all()]

    if request.method == 'POST' and is_composer:
        post_genre = Genre.objects.get(name=request.POST.get("genre"))
        post_composer = Composer.objects.get(user__username=request.user)
        song = Song(
            title=request.POST['title'],
            audio_file=request.FILES['audio_file'],
            description=request.POST['description'],
            post=request.POST.get('post', ''),
            genre=post_genre,
            composer=post_composer
        )
        song.save()

    if is_composer:
        context['art_name'] = user.composers.art_name
        context['genres'] = list(Genre.objects.all())
    favourite_genres = user.favourite_genres.all()
    favourite_composers = user.favourite_composers.all()
    if is_composer:
        songs = Song.objects.filter(
            Q(composer__in=favourite_composers)
            | Q(genre__in=favourite_genres)
            | Q(composer__user__username=user)).order_by('-date')
    else:
        songs = Song.objects.filter(
            Q(composer__in=favourite_composers)
            | Q(genre__in=favourite_genres)).order_by('-date')

    paginator = Paginator(songs, 10)
    page = request.GET.get('page', 1)
    is_paginated = True if paginator.num_pages > 10 else False
    songs = paginator.page(page)

    context['songs'] = songs
    context['is_composer'] = is_composer
    context['avatar'] = user.avatar
    context['full_name'] = user.get_full_name()
    context['bio'] = user.bio
    context['is_paginated'] = is_paginated

    return render(request, 'songs/feed.html', context)


@method_decorator(login_required, name="dispatch")
class ComposerDetailView(DetailView):
    template_name = "songs/composer/detail.html"
    model = Composer


@method_decorator(login_required, name="dispatch")
class ComposerCreateView(CreateView):
    template_name = "songs/composer/create.html"
    model = Composer

    fields = ('art_name',)
    success_url = reverse_lazy('songs:feed')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.user = self.request.user
        return super(ComposerCreateView, self).form_valid(form)


@method_decorator(login_required, name="dispatch")
class SongDetailView(DetailView):
    template_name = "songs/song/detail.html"
    model = Song


@method_decorator(composer_only, name="dispatch")
class SongChangeView(UpdateView):
    model = Song
    template_name = 'songs/song/change.html'
    fields = ('title', 'post', 'description', 'genre')

    success_url = reverse_lazy('songs:dashboard')


@method_decorator(composer_only, name="dispatch")
class SongDeleteView(DeleteView):
    model = Song
    success_url = reverse_lazy("songs:dashboard")
    template_name = "songs/song/delete.html"


@method_decorator(login_required, name="dispatch")
class GenreDetailView(DetailView):
    template_name = "songs/genre/detail.html"
    model = Genre


@login_required
def insert_comment(request):
    success = False
    user = User.objects.get(username=request.GET.get('username', False))
    song = Song.objects.get(pk=request.GET.get('song', False))
    text = request.GET.get('text', False)

    if user and song and text:
        comment = Comment(
            text=text,
            song=song,
            user=user
        )

        if comment:
            comment.save()
            success = True

    return JsonResponse({'comment_inserted': success})


@login_required
def get_genres(request):
    return JsonResponse({'genres': list(obj.name for obj in Genre.objects.all())})


@login_required
def get_composers(request):
    return JsonResponse({'composers': list(obj.art_name for obj in Composer.objects.all())})


@login_required
def get_songs(request):
    return JsonResponse({'songs': list(obj.title for obj in Song.objects.all())})


@login_required
def following(request):
    return render(request, 'songs/following.html')


@login_required
def unfollow(request):
    success = False
    artist = False
    if request.GET.get('value', False):
        arg = request.GET.get('value')
        if arg.startswith('btn_artist'):
            try:
                artist = Composer.objects.get(pk=int(arg.strip('btn_artist_')))
                user = User.objects.get(username=request.user.username)
                user.favourite_composers.remove(artist)
                success = True
                artist = True
            except:
                success = False
        elif arg.startswith('btn_genre'):
            try:
                genre = Genre.objects.get(pk=int(arg.strip('btn_genre_')))
                user = User.objects.get(username=request.user.username)
                user.favourite_genres.remove(genre)
                success = True
            except:
                success = False

    return JsonResponse({'success': success, 'artist': artist})


@login_required
def follow(request):
    success = False
    artist = False
    if request.GET.get('value', False):
        arg = request.GET.get('value')
        user = request.user
        if arg.startswith('btn_artist'):
            try:
                c = Composer.objects.get(pk=int(arg.strip('btn_artist')))
                if c.user != user:
                    user.favourite_composers.add(c)
                    success = True
                    artist = True
            except:
                success = False
        elif arg.startswith('btn_genre'):
            try:
                genre = Genre.objects.get(pk=int(arg.strip('btn_genre_')))
                user.favourite_genres.add(genre)
                success = True
            except:
                success = False

    return JsonResponse({'success': success, 'artist': artist})


@login_required
def search(request):
    category = request.GET.get('category', False)
    value = request.GET.get('search', False)

    if category and value:
        if category == 'songs':
            res = Song.objects.filter(title__contains=value)
        elif category == 'genres':
            res = Genre.objects.filter(name__contains=value)
        else:
            res = Composer.objects.filter(art_name__contains=value)

        return render(request, 'songs/results.html', {'results': list(res)})


@login_required
def like(request):
    success = False
    user = request.user
    song = Song.objects.get(pk=request.GET.get('pk'))
    if user and song:
        if song.likes.filter(user=user, song=song).count() > 0:
            song.likes.get(user=user, song=song).delete()
        else:
            Like(user=user, song=song).save()

        success = True
    return JsonResponse({'success': success})


@login_required
def rankings(request):
    composers = Composer.objects.all()
    composers_likes = list()
    song_likes = list()

    for composer in composers:
        tot = 0
        songs = Song.objects.filter(composer=composer)
        for song in songs:
            comments = Comment.objects.filter(song=song, date_time__gt=timezone.now() - timedelta(30)) \
                .exclude(user__composers=composer).count()
            tot += comments
        composers_likes.append((composer, tot))

    for song in Song.objects.all():
        song_likes.append((song, song.likes.all().count()))

    song_likes.sort(key=lambda obj: obj[1], reverse=True)
    composers_likes.sort(key=lambda obj: obj[1], reverse=True)

    return render(request, 'songs/ranking.html', {'songs': song_likes[:10], 'composers': composers_likes[:10]})


def daterange(start, end):
    for n in range(int((end - start).days) + 1):
        yield start + timedelta(n)


def get_data(user, start):
    likes = []
    comments = []

    for single_date in daterange(start, timezone.now()):
        likes.append(((single_date.year, single_date.month - 1, single_date.day),
                      Like.objects.filter(song__composer=user.composers, date__lte=single_date).count()))
        comments.append(((single_date.year, single_date.month - 1, single_date.day),
                        Comment.objects.filter(song__composer=user.composers, date_time__lte=single_date)
                         .exclude(user=user).count()))

    return likes, comments


@composer_only
def get_data_to_graph(request, *args, **kwargs):

    start = timezone.now() - timedelta(int(request.GET.get('period')))
    user = request.user
    likes, comments = get_data(user, start)

    return JsonResponse({'likes': likes, 'commenti': comments})


@composer_only
def dashboard(request):
    return render(request, 'songs/dashboard.html')

songs/templates/songs/base_logged.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'assets/css/home_style.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.min.css' %}" />
 <!--   <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">-->

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
<nav class="navbar navbar-light  bg-white">
    <div class="col-md-3">
        <a href="{% url 'songs:feed' %}" class="navbar-brand center"><h2><b>Sound Share</b></h2></a>
    </div>
    <div class="col-md-6">
        <form class="form-inline" action="{% url 'songs:search' %}">
            <div class="input-group w-100">
                <select id="seraching-for" class="custom-select col-md-3" name="category">
                    <option value="genres">Generi</option>
                    <option value="composers">Compositori</option>
                    <option value="songs">Brani</option>
                </select>
                <input id="search" type="text" class="form-control" name="search" aria-label="Recipient's username" aria-describedby="button-addon2" required />
                <div class="input-group-append">
                    <button class="btn btn-outline-primary" type="submit" id="button-addon2">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div  class="flex col-md-3">
        <div class="btn-group float-right">
            <button id="btnGroupDrop1" type="button" class="btn btn-link" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-3x fa-user-circle"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                {% if user.composers %}
                    <a class="dropdown-item" href="{% url 'songs:dashboard' %}"><i class="fa fa-dashboard"></i> Dashboard</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'songs:composer-create' %}"><i class="fa fa-user-plus"></i> Diventa compositore!</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'users:edit' %}"><i class="fa fa-cog"></i> Modifica account</a>
                <a class="dropdown-item" href="{% url 'users:logout' %}"><i class="fa fa-backward"></i> Logout</a>
            </div>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- Auto-Complete script section -->
<script>
  $(document).ready( function() {

      $.ajax({
                type: 'GET',
                url: '{% url 'songs:get-genres' %}',
                dataType: "json",
                success: function (data) {
                    $( "#search" ).autocomplete({
                        source: data.genres
                    });
                }
            })

    $('#seraching-for').on('change',function(){
        if ( $(this).val() === 'genres' ){
            $.ajax({
                type: 'GET',
                url: '{% url 'songs:get-genres' %}',
                dataType: "json",
                success: function (data) {
                    $( "#search" ).autocomplete({
                        source: data.genres
                    });
                }
            })
            }else if ( $(this).val() === 'songs' ){
            $.ajax({
                type: 'GET',
                url: '{% url 'songs:get-songs' %}',
                dataType: "json",
                success: function (data) {
                    $( "#search" ).autocomplete({
                        source: data.songs
                    });
                }
            })
            }else{
            $.ajax({
                type: 'GET',
                url: '{% url 'songs:get-composers' %}',
                dataType: "json",
                success: function (data) {
                    $( "#search" ).autocomplete({
                        source: data.composers
                    });
                }
            })}

        })
  } );
  </script>
<!-- End Auto-Complete script section -->

{% block script %}{% endblock %}
</body>

</html>

songs/templates/songs/dashboard.html
{% extends 'songs/base_logged.html' %}

{% block title %}
    Dashboard | Sound Share
{% endblock %}

{% block content %}
    <body>
    <div class="container gedf-wrapper">
        <div class="card">
            <div class="card-header">
                <div class="d-inline-flex justify-content-between w-100">
                    <div class="h3 mb-0">
                        Andamento interazioni:
                    </div>
                    <select id="period" class="custom-select col-md-3">
                        <option value=7>Ultimi 7 giorni</option>
                        <option value=30>Ultimi 30 giorni</option>
                        <option value="365">Ultimi 365 giorni</option>
                    </select>
                </div>
            </div>
            <div class="card-body">
                <div id="chartContainer" style="height: 370px; width: 100%;"></div>
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                <div class="h3 mb-0 card-title">
                    I miei brani:
                </div>
            </div>
            <div class="card-body">
                <div class="card">
                    <ul id="genre_list" class="list-group list-group-flush">

                        {% for el in user.composers.songs.all %}
                            <li class="list-group-item" style="display: block">
                                <div class="d-inline-flex justify-content-between col-12">
                                    <div class="my-auto col-md-3">
                                        <h5 class="my-auto">
                                            <a href="{% url 'songs:song-detail' el.pk %}">
                                                {{ el.title }}
                                            </a>
                                        </h5>
                                    </div>
                                    <div class="d-inline-flex justify-content-end col-md-4">
                                        <a href="{% url 'songs:song-change' el.pk %}" class="mr-2">
                                            <button type="button" class="btn btn-warning">
                                                Modifica
                                            </button>
                                        </a>
                                        <a href="{% url 'songs:song-delete' el.pk %}">
                                            <button type="button" class="btn btn-danger">
                                                Elimina
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>



    </div>


    </body>
{% endblock %}

{% block script %}
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script>

        $(document).ready(refresh($("#period").children("option:selected").val()))

        $("#period").on('change', function () {
            refresh($("#period").children("option:selected").val())
        })

        function refresh(period) {
            var commenti, likes;


            $.ajax({
                type: 'GET',
                url: '{% url 'songs:refresh-data' %}',
                data:{
                    'period': period
                },
                dataType: "json",
                success: function (data) {
                    likes = [];
                    commenti = [];
                    var limit = data.likes.length;
                    for (var i = 1; i < limit; i += 1) {
                        likes.push({
                            x: new Date(data.likes[i][0][0], data.likes[i][0][1], data.likes[i][0][2] ),
                            y: data.likes[i][1],
                        });
                        commenti.push({
                            x: new Date(data.commenti[i][0][0], data.commenti[i][0][1], data.commenti[i][0][2] ),
                            y: data.commenti[i][1],
                        });
                    }
                    var chart = new CanvasJS.Chart("chartContainer", {
                        animationEnabled: true,
                        axisX: {
                            valueFormatString: "DD MMM YY"
                        },
                        axisY: {
                            title: "# Interazioni",
                            includeZero: false,
                        },
                        legend:{
                            cursor: "pointer",
                            fontSize: 16,
                            itemclick: toggleDataSeries
                        },
                        toolTip:{
                            shared: true
                        },
                        data: [{
                            name: "Likes",
                            type: "spline",
                            showInLegend: true,
                            dataPoints: likes,
                        },
                            {
                                name: "Commenti",
                                type: "spline",
                                showInLegend: true,
                                dataPoints: commenti,
                            }]
                    });
                    chart.render();

                    function toggleDataSeries(e){
                        if (typeof(e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                            e.dataSeries.visible = false;
                        }
                        else{
                            e.dataSeries.visible = true;
                        }
                        chart.render();
                    }
                }
            })
        }
    </script>
{% endblock %}

songs/templates/songs/following.html
{% extends 'songs/base_logged.html' %}
{% block title %}{{ user.username }} | Following{% endblock %}

{% block content %}

    <div class="container">

        <form class="form-group mt-3">
            <label for="filter" class = "mr-2">Inserisci il nome del genere o dell'artista:</label>
            <input name="filter" type="text" class="form-control custom-control-inline" id="filter" placeholder="Filtra..." required />
        </form>

        <div class="row"><hr style="2width: 100%; height: 2px; " /></div>
        <div class="card">
            <div class="card-header">
                <h3 class="pb-0">
                    Generi
                </h3>
            </div>
            <div class="card-body">
                <div class="card">
                    <ul id="genre_list" class="list-group list-group-flush">

                        {% for genre in user.favourite_genres.all %}
                            <li class="list-group-item" style="display: block">
                                <div class="d-inline-flex justify-content-between col-12">
                                    <div class="my-auto col-md-3">
                                        <a href="{% url 'songs:genre-detail' genre.pk %}">
                                            <h5 class="my-auto">
                                                {{ genre.name }}
                                            </h5>
                                        </a>
                                    </div>
                                    <div class="d-inline-flex justify-content-end col-md-4">
                                        <form class="form-inline">
                                            <button type="button" class="btn btn-danger" value="btn_genre_{{ genre.pk }}" onclick="del('btn_genre_{{ genre.pk }}')">
                                                Rimuovi
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row"><hr style="width: 100%; height: 2px; " /></div>
        <div class="card">
            <div class="card-header">
                <h3 class="pb-0">
                    Artisti
                </h3>
            </div>
            <div class="card-body">
                <div class="card">
                    <ul id="my_list" class="list-group list-group-flush">

                        {% for artist in user.favourite_composers.all %}
                            <li class="list-group-item composer" style="display: block">
                                <div class="d-inline-flex justify-content-between col-12">
                                    <div class="my-auto col-md-3">
                                        <a href="{% url 'songs:composer-detail' artist.pk %}">
                                            <h5 class="my-auto">
                                                {{ artist.art_name }}
                                            </h5>
                                        </a>
                                    </div>
                                    <div class="d-inline-flex justify-content-end col-md-4">
                                        <form class="form-inline">
                                            <button type="button" class="btn btn-danger" value="btn_artist_{{ artist.pk }}" onclick="del('btn_artist_{{ artist.pk }}')">
                                                Rimuovi
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block script %}
    <script type="text/javascript">
            $("#filter").on("keyup", function() {
                let input, filter, ul_artist, li_artist,ul, li, a, i, txtValue;
                input = document.getElementById('filter');
                filter = input.value.toUpperCase();
                ul_artist = document.getElementById("my_list");
                li_artist = ul_artist.getElementsByTagName('li');

                // Loop through all list items, and hide those who don't match the search query
                for (i = 0; i < li_artist.length; i++) {
                    a = li_artist[i].getElementsByTagName('h5')[0];
                    txtValue = a.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        li_artist[i].style.display = "block";
                    } else {
                        li_artist[i].style = "display:none !important";
                    }
                }

                ul = document.getElementById("genre_list");
                li = ul.getElementsByTagName('li');

                // Loop through all list items, and hide those who don't match the search query
                for (i = 0; i < li.length; i++) {
                    a = li[i].getElementsByTagName('h5')[0];
                    txtValue = a.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        li[i].style.display = "block";
                    } else {
                        li[i].style = "display:none !important";
                    }
                }
            });

            function del(value) {
                $.ajax({
                type: 'GET',
                url: '{% url 'songs:unfollow' %}',
                data: {
                    'value' : value,
                },

                dataType: "json",
                success: function (data) {
                    if (data.success){
                        if(data.artist)
                            $("#my_list").load(" #my_list > *");
                        else
                            $("#genre_list").load(" #genre_list> *");
                    }else{
                        alert("Rimozione non riuscita!");
                    }
                }
            })
            }
    </script>
{% endblock %}