progetto_tecnologie_web_2020/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', 'users')),
    path('admin/', admin.site.urls),
    path('songs/', include('songs.urls')),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from songs import views

app_name = 'songs'

urlpatterns = [
    path('feed/', views.feed, name='feed'),
    path('composer/<int:pk>/detail', views.ComposerDetailView.as_view(), name='composer-detail'),

    path('song/<int:pk>/detail', views.SongDetailView.as_view(), name='song-detail'),
    path('song/<int:pk>/modify', views.SongChangeView.as_view(), name='song-change'),
    path('song/<int:pk>/delete', views.SongDeleteView.as_view(), name='song-delete'),


    path('genre/<int:pk>/detail', views.GenreDetailView.as_view(), name='genre-detail'),

    path('insert_comment', views.insert_comment, name='insert-comment'),

    path('results', views.search, name='search'),
    path('get_genres', views.get_genres, name='get-genres'),
    path('get_songs', views.get_songs, name='get-songs'),
    path('get_composers', views.get_composers, name='get-composers'),

    path('following', views.following, name='following'),
    path('unfollow', views.unfollow, name='unfollow'),
    path('follow', views.follow, name='follow'),
    path('like', views.like, name='like'),


    path('become_composer', views.ComposerCreateView.as_view(), name='composer-create'),

    path('rankings', views.rankings, name="rankings"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('refresh-graph', views.get_data_to_graph, name="refresh-data")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/models.py
from django.db import models
from users.models import User


## @file models.py
#  @package songs/model
#  Definizione del database per l'app "songs".
#
#  In questo modulo python vengono definite le tabelle e le relazioni relative \
#  all'applicazione songs
#


## Table: Genre
#  @class Genre
#
# Contains all musical genres created by admin.
class Genre(models.Model):

    ## @var name
    #  Name of musical genre
    name = models.CharField(max_length=30, unique=True,)

    ## @var description
    #  Description of the musical genre provided by admin
    description = models.TextField()

    ## @var favourite_genres
    #  Reifiication of the User-Genre relation
    #
    #  ManyToMany field (see django documentation at https://docs.djangoproject.com/en/4.0/topics/db/examples/many_to_many/) \
    #  between User and Genre. It tells if a certain <USER> likes a certain <GENRE>
    favourite_genres = models.ManyToManyField(User, related_name='favourite_genres', blank=True)

    ## Returns songs that belong to a certain <GENRE>
    #  @param self Instance of a musical genre
    #
    #  Given a certain instance of a genre, returns all songs in database that belong to this genre
    def get_songs(self):
        return list(self.songs.all())

    def __str__(self):
        return self.name


## Table: song
#  @class Song
#
#   Contains all the songs uploaded by users
class Song(models.Model):

    ## @var title
    #  Title of the song
    title = models.CharField(max_length=40, verbose_name="Titolo")

    ## @var audio_file
    #  Audio file related to the song
    #
    #  The audio file is stored in the folder indicated by "upload_to" parameter
    audio_file = models.FileField(upload_to='songs/',
                                  verbose_name='AudioFile')

    ## @var date
    #  The date the song was uploaded
    date = models.DateTimeField(auto_now_add=True)

    ## @var description
    #  Description of the song provided by user
    description = models.TextField(verbose_name='Descrizione')

    ## @var @post
    #  Post related to the song, provided by user
    post = models.TextField()

    ## @var genre
    #  Genre of the song
    #
    #  Foreign key to table Genre
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='songs', verbose_name='Genere')

    ## @var composer
    #  Composer of the song
    #
    #  Foreign key to table User
    composer = models.ForeignKey('Composer', on_delete=models.CASCADE, related_name='songs')

    ## Returns the comments related to a song
    #  @param self Istance of a song
    #
    #  Given an instance of a song, returns the comments for that song sorted by the date of submission.
    def get_comments(self):
        return list(self.comments.all().order_by('-date_time'))

    ## Return the list of user that liked the song
    #  @param self Instance of a song
    def get_likes(self):
        return [like.user for like in self.likes.all()]


## Table: like
#  @class Like
#
#  Reification of the NtoN relation Users-Songs. Contains the likes instances between songs and users.
#  It defines the name of the relation in order to make the relation accessible from the tables song and user.
#  It also include the date of the like.
class Like(models.Model):

    ## @var song
    #  Foreign key totable song.
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name='likes')

    ## @var user
    #  Foreign key to table user.
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')

    ## @var date
    #  Date of submission of the like.
    date = models.DateField(auto_now_add=True)


## Table comment
#  @class Comment
#
#  It contains song's comments submitted by users.
class Comment(models.Model):

    ## @var text
    #  Text of the comment
    text = models.TextField()

    ## @var date_time
    #  Date and hour of submission of the comment
    date_time = models.DateTimeField(auto_now_add=True)

    ## @var song
    #  Foreign key to song's table.
    song = models.ForeignKey(Song, on_delete=models.CASCADE, related_name='comments')

    ## @var user
    #  Foreign key to users' table
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')


## Table: composer
#  @class Composer
#
#  Contains users that are also composers.
#  An user can be either a simle user or a composer:
#      - user: only listens to composers' songs
#      - composer: can listen and upload songs
class Composer(models.Model):

    ## @var user
    #  OneToOne field to User table.
    #
    #  It specifies that the user is also a composer.
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='composers')

    ## @var art_name
    #  Art-name of the composer.
    art_name = models.CharField(max_length=30, unique=True, verbose_name="nome d'arte")

    ## @var favourite_composers
    #  Reification of the relation Users-Composers (user likes composers, a composer is liked by many users)
    favourite_composers = models.ManyToManyField(User, related_name='favourite_composers')

    ## @class: Composer.Meta
    #  Additional informations for class Composer
    class Meta:

        verbose_name = 'compositore'
        verbose_name_plural = 'compositori'

    ## Returns composer's full name
    #  @param self Composer's instance.
    def get_full_name(self):
        return self.user.get_full_name()

    ## Returns composer's list of followers
    #  @param self Composer's instance.
    def get_followers(self):
        return list(self.favourite_composers.all())

    ## Returns composer's profile picture.
    #  @param self Composer's instance.
    def get_avatar(self):
        return self.user.avatar

songs/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from datetime import timedelta

from songs.decorators import composer_only
from songs.models import Song, Genre, Composer, Comment, Like
from users.models import User


@login_required
def feed(request):
    context = dict()

    user = request.user
    is_composer = user.username in [obj.user.username for obj in Composer.objects.all()]

    if request.method == 'POST' and is_composer:
        post_genre = Genre.objects.get(name=request.POST.get("genre"))
        post_composer = Composer.objects.get(user__username=request.user)
        song = Song(
            title=request.POST['title'],
            audio_file=request.FILES['audio_file'],
            description=request.POST['description'],
            post=request.POST.get('post', ''),
            genre=post_genre,
            composer=post_composer
        )
        song.save()

    if is_composer:
        context['art_name'] = user.composers.art_name
        context['genres'] = list(Genre.objects.all())
    favourite_genres = user.favourite_genres.all()
    favourite_composers = user.favourite_composers.all()
    if is_composer:
        songs = Song.objects.filter(
            Q(composer__in=favourite_composers)
            | Q(genre__in=favourite_genres)
            | Q(composer__user__username=user)).order_by('-date')
    else:
        songs = Song.objects.filter(
            Q(composer__in=favourite_composers)
            | Q(genre__in=favourite_genres)).order_by('-date')

    paginator = Paginator(songs, 10)
    page = request.GET.get('page', 1)
    is_paginated = True if paginator.num_pages > 10 else False
    songs = paginator.page(page)

    context['songs'] = songs
    context['is_composer'] = is_composer
    context['avatar'] = user.avatar
    context['full_name'] = user.get_full_name()
    context['bio'] = user.bio
    context['is_paginated'] = is_paginated

    return render(request, 'songs/feed.html', context)


@method_decorator(login_required, name="dispatch")
class ComposerDetailView(DetailView):
    template_name = "songs/composer/detail.html"
    model = Composer


@method_decorator(login_required, name="dispatch")
class ComposerCreateView(CreateView):
    template_name = "songs/composer/create.html"
    model = Composer

    fields = ('art_name',)
    success_url = reverse_lazy('songs:feed')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.user = self.request.user
        return super(ComposerCreateView, self).form_valid(form)


@method_decorator(login_required, name="dispatch")
class SongDetailView(DetailView):
    template_name = "songs/song/detail.html"
    model = Song


@method_decorator(composer_only, name="dispatch")
class SongChangeView(UpdateView):
    model = Song
    template_name = 'songs/song/change.html'
    fields = ('title', 'post', 'description', 'genre')

    success_url = reverse_lazy('songs:dashboard')


@method_decorator(composer_only, name="dispatch")
class SongDeleteView(DeleteView):
    model = Song
    success_url = reverse_lazy("songs:dashboard")
    template_name = "songs/song/delete.html"


@method_decorator(login_required, name="dispatch")
class GenreDetailView(DetailView):
    template_name = "songs/genre/detail.html"
    model = Genre


@login_required
def insert_comment(request):
    success = False
    user = User.objects.get(username=request.GET.get('username', False))
    song = Song.objects.get(pk=request.GET.get('song', False))
    text = request.GET.get('text', False)

    if user and song and text:
        comment = Comment(
            text=text,
            song=song,
            user=user
        )

        if comment:
            comment.save()
            success = True

    return JsonResponse({'comment_inserted': success})


@login_required
def get_genres(request):
    return JsonResponse({'genres': list(obj.name for obj in Genre.objects.all())})


@login_required
def get_composers(request):
    return JsonResponse({'composers': list(obj.art_name for obj in Composer.objects.all())})


@login_required
def get_songs(request):
    return JsonResponse({'songs': list(obj.title for obj in Song.objects.all())})


@login_required
def following(request):
    return render(request, 'songs/following.html')


@login_required
def unfollow(request):
    success = False
    artist = False
    if request.GET.get('value', False):
        arg = request.GET.get('value')
        if arg.startswith('btn_artist'):
            try:
                artist = Composer.objects.get(pk=int(arg.strip('btn_artist_')))
                user = User.objects.get(username=request.user.username)
                user.favourite_composers.remove(artist)
                success = True
                artist = True
            except:
                success = False
        elif arg.startswith('btn_genre'):
            try:
                genre = Genre.objects.get(pk=int(arg.strip('btn_genre_')))
                user = User.objects.get(username=request.user.username)
                user.favourite_genres.remove(genre)
                success = True
            except:
                success = False

    return JsonResponse({'success': success, 'artist': artist})


@login_required
def follow(request):
    success = False
    artist = False
    if request.GET.get('value', False):
        arg = request.GET.get('value')
        user = request.user
        if arg.startswith('btn_artist'):
            try:
                c = Composer.objects.get(pk=int(arg.strip('btn_artist')))
                if c.user != user:
                    user.favourite_composers.add(c)
                    success = True
                    artist = True
            except:
                success = False
        elif arg.startswith('btn_genre'):
            try:
                genre = Genre.objects.get(pk=int(arg.strip('btn_genre_')))
                user.favourite_genres.add(genre)
                success = True
            except:
                success = False

    return JsonResponse({'success': success, 'artist': artist})


@login_required
def search(request):
    category = request.GET.get('category', False)
    value = request.GET.get('search', False)

    if category and value:
        if category == 'songs':
            res = Song.objects.filter(title__contains=value)
        elif category == 'genres':
            res = Genre.objects.filter(name__contains=value)
        else:
            res = Composer.objects.filter(art_name__contains=value)

        return render(request, 'songs/results.html', {'results': list(res)})


@login_required
def like(request):
    success = False
    user = request.user
    song = Song.objects.get(pk=request.GET.get('pk'))
    if user and song:
        if song.likes.filter(user=user, song=song).count() > 0:
            song.likes.get(user=user, song=song).delete()
        else:
            Like(user=user, song=song).save()

        success = True
    return JsonResponse({'success': success})


@login_required
def rankings(request):
    composers = Composer.objects.all()
    composers_likes = list()
    song_likes = list()

    for composer in composers:
        tot = 0
        songs = Song.objects.filter(composer=composer)
        for song in songs:
            comments = Comment.objects.filter(song=song, date_time__gt=timezone.now() - timedelta(30)) \
                .exclude(user__composers=composer).count()
            tot += comments
        composers_likes.append((composer, tot))

    for song in Song.objects.all():
        song_likes.append((song, song.likes.all().count()))

    song_likes.sort(key=lambda obj: obj[1], reverse=True)
    composers_likes.sort(key=lambda obj: obj[1], reverse=True)

    return render(request, 'songs/ranking.html', {'songs': song_likes[:10], 'composers': composers_likes[:10]})


def daterange(start, end):
    for n in range(int((end - start).days) + 1):
        yield start + timedelta(n)


def get_data(user, start):
    likes = []
    comments = []

    for single_date in daterange(start, timezone.now()):
        likes.append(((single_date.year, single_date.month - 1, single_date.day),
                      Like.objects.filter(song__composer=user.composers, date__lte=single_date).count()))
        comments.append(((single_date.year, single_date.month - 1, single_date.day),
                        Comment.objects.filter(song__composer=user.composers, date_time__lte=single_date)
                         .exclude(user=user).count()))

    return likes, comments


@composer_only
def get_data_to_graph(request, *args, **kwargs):

    start = timezone.now() - timedelta(int(request.GET.get('period')))
    user = request.user
    likes, comments = get_data(user, start)

    return JsonResponse({'likes': likes, 'commenti': comments})


@composer_only
def dashboard(request):
    return render(request, 'songs/dashboard.html')

songs/templates/songs/composer/create.html
{% extends 'songs/base_logged.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Language create{% endblock %}

{% block content %}

    <div class="container form-group">
        <form method="post">
            <h3 class="mt-4">Diventa compositore per accedere a tutte le potenzialità della piattaforma:</h3>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="justify-content-end d-inline-flex w-100">
            <button type="submit" class="btn btn-primary">Salva</button>
        </div>
        </form>


    </div>

{% endblock %}

songs/templates/songs/composer/detail.html
{% extends 'songs/base_logged.html' %}

{% block title %}{{ object.art_name }}{% endblock %}

{% block content %}

    <div class="container gedf-wrapper">
        <div class="row">
            <div class="col-md-8">
                <div class="card h-100">
                    <div class="card-header d-inline-flex justify-content-between">
                        <div class="h5 my-auto">Scheda compositore</div>
                        {% if user.username != object.user.username %}
                            <div id="btn_follow">
                                {% if user in object.get_followers %}
                                <button class="btn btn-danger" onclick="unfollow('btn_artist_{{ object.pk }}')">Rimuovi ai preferiti</button>
                            {% else %}
                                <button class="btn btn-success" onclick="follow('btn_artist_{{ object.pk }}')">Aggiungi dai preferiti</button>
                            {% endif %}
                            </div>
                        {% endif %}

                    </div>
                    <div class="card-body">
                        <div CLASS="row">
                            <div class="col-md-6">
                                <p class="text-left"><b>NOME</b></p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-left">{{ object.user.get_full_name }}</p>
                            </div>
                        </div>
                        <div CLASS="row">
                            <div class="col-md-6">
                                <p class="text-left"><b>NOME D'ARTE</b></p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-left">{{ object.art_name }}</p>
                            </div>
                        </div>
                        <div CLASS="row">
                            <div class="col-md-6">
                                <p class="text-left"><b>MAIL</b></p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-left">{{ object.user.email }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <p> <hr /> </p>
                        </div>
                        <div CLASS="row">
                            <div class="col-md-6">
                                <p class="text-left"><b>DATA PRIMO ACCESSO</b></p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-left">{{ object.user.date_joined.date }}</p>
                            </div>
                        </div>
                        <div CLASS="row">
                            <div class="col-md-6">
                                <p class="text-left"><b>NUMERO DI BRANI CARICATI</b></p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-left">{{ object.songs.count }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <p> <hr /> </p>
                        </div>
                        <div CLASS="row">
                            <div class="col-md-6">
                                <p class="text-left"><b>ABOUT ME</b></p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-left">{{ object.user.bio }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="border rounded bg-white">
                    <img src="{{ object.user.avatar.url }}" class="w-100 border rounded" />
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card gedf-wrapper">
                    <div class="card-header">
                        <div class=" h5 m-0">Ultimi brani caricati</div>
                    </div>
                    <div class="card-body">
                               <div class="card">
                    <ol id="genre_list" class="list-group list-group-flush">
                        {% for song in object.songs.all|dictsortreversed:"date" %}
                            <li class="list-group-item">
                                <div class="d-inline-flex justify-content-between col-12">
                                    <a href="{% url 'songs:song-detail' song.pk %}" class="d-inline-flex">
                                        <div class="mr-2">
                                            <i class="fa fa-play-circle fa-2x"></i>
                                        </div>
                                        <div class="h5 my-auto">
                                            {{ song.title }}
                                        </div>
                                    </a>
                                    <div class="h6 text text-muted my-auto">
                                        {{ song.date.date }}
                                    </div>

                                </div>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
                    </div>

                </div>
            </div>

        </div>

    </div>

{% endblock %}
{% block script %}
    <script type="text/javascript">
            function unfollow(value) {
                $.ajax({
                type: 'GET',
                url: '{% url 'songs:unfollow' %}',
                data: {
                    'value' : value,
                },

                dataType: "json",
                success: function (data) {
                    if (data.success){
                        $("#btn_follow").load(" #btn_follow> *");
                    }else{
                        alert("Rimozione non riuscita!");
                    }
                }
            })
            }

            function follow(value) {
                $.ajax({
                type: 'GET',
                url: '{% url 'songs:follow' %}',
                data: {
                    'value' : value,
                },

                dataType: "json",
                success: function (data) {
                    if (data.success){
                        $("#btn_follow").load(" #btn_follow> *");
                    }else{
                        alert("Modifica non riuscita!");
                    }
                }
            })
            }
    </script>
{% endblock %}