progetto_tecnologie_web_2020/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', 'users')),
    path('admin/', admin.site.urls),
    path('songs/', include('songs.urls')),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('accounts/reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from songs import views

app_name = 'songs'

urlpatterns = [
    path('feed/', views.feed, name='feed'),
    path('composer/<int:pk>/detail', views.ComposerDetailView.as_view(), name='composer-detail'),

    path('song/<int:pk>/detail', views.SongDetailView.as_view(), name='song-detail'),
    path('song/<int:pk>/modify', views.SongChangeView.as_view(), name='song-change'),
    path('song/<int:pk>/delete', views.SongDeleteView.as_view(), name='song-delete'),


    path('genre/<int:pk>/detail', views.GenreDetailView.as_view(), name='genre-detail'),

    path('insert_comment', views.insert_comment, name='insert-comment'),

    path('results', views.search, name='search'),
    path('get_genres', views.get_genres, name='get-genres'),
    path('get_songs', views.get_songs, name='get-songs'),
    path('get_composers', views.get_composers, name='get-composers'),

    path('following', views.following, name='following'),
    path('unfollow', views.unfollow, name='unfollow'),
    path('follow', views.follow, name='follow'),
    path('like', views.like, name='like'),


    path('become_composer', views.ComposerCreateView.as_view(), name='composer-create'),

    path('rankings', views.rankings, name="rankings"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('refresh-graph', views.get_data_to_graph, name="refresh-data")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.user_change_view, name='edit'),
    path('password/', views.change_password, name='change-psw'),
    path('verify/<str:user_id_b64>/<str:user_token>', views.verify_user_email, name='verify-user-email'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">

    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>

</head>
<body>
    {% block navbar %}{% endblock %}
<div id="site-main-page" class="container mt-3 pt-3">
    {% block content %}

    {% endblock %}

</div>

<script>{% block script %} {% endblock %}</script>
</body>
</html>

templates/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/icofont/icofont.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <title>Sound Share - HomePage</title>
</head>

<body>
<!-- ======= Header ======= -->
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <h1 class="logo mr-auto"><a href="">Sound Share</a></h1>

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="active"><a href="#hero">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="{% url 'users:login' %}">Login</a></li>
            </ul>
        </nav><!-- .nav-menu -->

        <a href="{% url 'users:register' %}" class="get-started-btn scrollto">Registrati</a>

    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">

    <div class="container">
        <div class="row">
            <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
                <h1>Sound Share</h1>
                <h2>Entra in contatto con i migliori artisti online!</h2>
                <div class="d-flex">
                    <a href="{% url 'users:register' %}" class="btn-get-started scrollto">Registrati</a>
                    <a href="{% url 'users:login' %}" class="btn-get-started_grey scrollto">Login</a>
                </div>
            </div>
            <div class="col-lg-6 order-1 order-lg-2 hero-img">
                <img src="{% static 'assets/img/hero-img.png' %}" class="img-fluid animated" alt="">
            </div>
        </div>
    </div>

</section><!-- End Hero -->

<main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <img src="{% static 'assets/img/about.png' %}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-6 pt-4 pt-lg-0 content">
                    <h3>Cos'è Sound Share?</h3>
                    <p class="font-italic">
                        Sound Share è una semplice piattaforma che ti permette di ascoltare e commentare tutti i pezzi prodotti
                        dai tuoi artisti preferiti in anteprima! Ti basta creare un account gratuito per ascoltare nuovi
                        brani e caricare i tuoi.
                    </p>
                    <ul>
                        <li><i class="icofont-check-circled"></i> Ascolta i tuoi artisti e generi preferiti!</li>
                        <li><i class="icofont-check-circled"></i> Commenta i nuovi brani parlando direttamente con gli
                            artisti!
                        </li>
                        <li><i class="icofont-check-circled"></i> Fatti notare caricando le tue ultime creazioni!</li>
                    </ul>
                    <p>
                        La piattaforma ti permette, infatti, di caricare i tuoi pezzi, e farli ascoltare direttamente a
                        tutti i tuoi follower, di comparire in classifiche e di pubblicare la tua musica!
                    </p>
                </div>
            </div>

        </div>
    </section><!-- End About Section -->
</main>


<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="container footer-bottom clearfix">
        <div class="copyright">
            &copy; Copyright <strong><span>Sound Share</span></strong> 2020.
        </div>
        <div class="social-links">
            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
<script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>